### ISSUE TITLE
[META] refactor context menu

### ISSUE THREAD

**Issue by asamuzaK** [asamuzaK/sidebarTabs#48]
Refactor context menu handling after related bugs are fixed.

* [x] [1280347 - Add ability to provide custom HTML elements working as alias of existing Firefox UI items, especially tabs](https://bugzilla.mozilla.org/show_bug.cgi?id=1280347)
* [x] [1367160 - Consider removing default context menu items in extension frames](https://bugzilla.mozilla.org/show_bug.cgi?id=1367160)
* [ ] [1416839 - Restrict context menus from showing up in the sidebar](https://bugzilla.mozilla.org/show_bug.cgi?id=1416839)
* [x] [1482529 - Implement &quot;visible&quot; parameter in menus.create and menus.update](https://bugzilla.mozilla.org/show_bug.cgi?id=1482529)
